### ISSUE TITLE
Code won't start

### ISSUE THREAD

**Issue by Fhoogeveen** [llagendijk/iskra-me162#1]
good evening,

the code won't start at a RPI 3 
i'f got the following error code: 
 
pi@HuisAutomatisering:~/iskra-me162 $ sudo iskra-me162
Traceback (most recent call last):
  File "/usr/local/bin/iskra-me162", line 23, in <module>
    from parse import *
ImportError: No module named 'parse'

if i hash the :
from parse import *
from parse import compile

the program runs and display a Telegram from te ISKRA-MT174
but can not sent data to Domoticz.

what could i do to get the program running?

Greeds
Frank Hoogeveen

**Comment by llagendijk** [comment]
On Sat, 2018-03-03 at 22:21 +0000, Fhoogeveen wrote:
> good evening,
> the code won't start at a RPI 3
> i'f got the following error code:
> pi@HuisAutomatisering:~/iskra-me162 $ sudo iskra-me162
> Traceback (most recent call last):
> File "/usr/local/bin/iskra-me162", line 23, in 
> from parse import *
> ImportError: No module named 'parse'
> if i hash the :
> from parse import *
> from parse import compile
> the program runs and display a Telegram from te ISKRA-MT174
> but can not sent data to Domoticz.
> what could i do to get the program running?
> Greeds
> Frank Hoogeveen
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
gewoon python3-parse installeren: apt-get install python3-parse.
Er is mogelijk nog een package wat je moet installeren, mogelijk heb je
dat al...
groeten, Louis

**Comment by Fhoogeveen** [comment]
Beste Louis,
Nederlands praat toch makkelijker.

het lijkt er inderdaad op dat ik een python3 module mis.
apt-get install python3-parse werkt bij mij niet.
kan in aptitude het "pakket" ook niet vinden.
apt-get install python-parse installeert wel.
maar hiermee gaat de code nog niet werken.

wat kan ik het beste doen ?

Frank
