### ISSUE TITLE
Iskra -mt171

### ISSUE THREAD

**Issue by yctn** [llagendijk/iskra-me162#2]
im trying to run ur script aganst a iskra mt-171 but im getting this error:

Meter Reading failed at  2018-09-13 23:04:22 will continue
sleeping for 79 seconds
Open COM port /dev/ttyUSB0 at 300 baud
Send initialization: /?<CR><LF>
Initialization done.
IR-baud = 300
Sent: <ACK>000
Datatransfer complete.
Number of received elements: 12
Array of received elements: 
['1-0:0.0.0*255(70107655)',
 '1-0:0.2.0*255(1.03)',
 '0-0:C.1.0*255(70107655)',
 '0-0:C.1.6*255(FDF5)',
 '1-0:1.8.0*255(0000138.662*kWh)',
 '1-0:1.8.1*255(0000000.000*kWh)',
 '1-0:1.8.2*255(0000138.662*kWh)',
 '1-0:2.8.0*255(0000879.528*kWh)',
 '1-0:2.8.1*255(0000000.000*kWh)',
 '1-0:2.8.2*255(0000879.528*kWh)',
 '0-0:F.F.0*255(0000000)',
 '!']
Telegram ontvangen op: 2018-09-13 23:05:53
Process new readings
Previous readings found,  update domoticz
Traceback (most recent call last):
  File "./iskra-me162", line 302, in <module>
    main()
  File "./iskra-me162", line 293, in main
    do_work()
  File "./iskra-me162", line 258, in do_work
    consumption = int((current_readings.total_usage - previous_readings.total_usage) / interval * 3600)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by llagendijk** [comment]
On Thu, 2018-09-13 at 14:07 -0700, yctn wrote:
> im trying to run ur script aganst a iskra mt-171 but im getting this
> error:
> 
> Meter Reading failed at  2018-09-13 23:04:22 will continue
> 
> sleeping for 79 seconds
> 
> Open COM port /dev/ttyUSB0 at 300 baud
> 
> Send initialization: /?
> 
> Initialization done.
> 
> IR-baud = 300
> 
> Sent: 000
> 
> Datatransfer complete.
> 
> Number of received elements: 12
> 
> Array of received elements:
> 
> ['1-0:0.0.0255(70107655)',
> 
> '1-0:0.2.0255(1.03)',
> 
> '0-0:C.1.0255(70107655)',
> 
> '0-0:C.1.6255(FDF5)',
> 
> '1-0:1.8.0255(0000138.662kWh)',
> 
> '1-0:1.8.1255(0000000.000kWh)',
> 
> '1-0:1.8.2255(0000138.662kWh)',
> 
> '1-0:2.8.0255(0000879.528kWh)',
> 
> '1-0:2.8.1255(0000000.000kWh)',
> 
> '1-0:2.8.2255(0000879.528kWh)',
> 
> '0-0:F.F.0*255(0000000)',
> 
> '!']
> 
> Telegram ontvangen op: 2018-09-13 23:05:53
> 
> Process new readings
> 
> Previous readings found,  update domoticz
> 
> Traceback (most recent call last):
> 
> File "./iskra-me162", line 302, in 
> 
> main()
> 
> File "./iskra-me162", line 293, in main
> 
> do_work()
> 
> File "./iskra-me162", line 258, in do_work
> 
> consumption = int((current_readings.total_usage -
> previous_readings.total_usage) / interval * 3600)
> 
> TypeError: unsupported operand type(s) for -: 'NoneType' and
> 'NoneType'
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/llagendij
> k/iskra-me162","title":"llagendijk/iskra-me162","subtitle":"GitHub
> repository","main_image_url":"
> https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open
>  in GitHub","url":"
> https://github.com/llagendijk/iskra-me162"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Iskra
>  -mt171 (#2)"}],"action":{"name":"View Issue","url":"
> https://github.com/llagendijk/iskra-me162/issues/2"}}}
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/llagendijk/iskra-me162/issues/2",
> "url": "https://github.com/llagendijk/iskra-me162/issues/2",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> "title": "Iskra -mt171 (#2)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**yctn**",
> "activityImage": "
> https://assets-cdn.github.com/images/email/message_cards/avatar.png",
> "activitySubtitle": "@yctn",
> "facts": [
> {
> "name": "Repository: ",
> "value": "llagendijk/iskra-me162"
> },
> {
> "name": "Issue #: ",
> "value": 2
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\":
> \"IssueComment\",\n\"repositoryFullName\": \"llagendijk/iskra-
> me162\",\n\"issueId\": 2,\n\"IssueComment\":
> \"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
> \"llagendijk/iskra-me162\",\n\"issueId\": 2\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> "uri": "https://github.com/llagendijk/iskra-me162/issues/2"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
> 379639741\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]
It looks as if the MT171 has a different formatting of identifiers for
the values sent:
the code is expecting values like C.1.0 for the serial number of the
meter, where I see here: 
0-0:C.1.0255(70107655)
So you probably need to change the patterns in the class MeterReadings
tp match the strings you get.
It will help if you just change print_debug=2 in the config file (in
/etc/default/iskra-me162 to see what happens


I don't have the me162 anymore, so Icanmnot check any more what the
exect format is that the ME162 sends. I know that I got the format from
the manual for the meter I found on the internet (attached). Maybe you
can find a similar manual for your meter and adapt the MeterReadings
class?


BR, Louis

**Comment by jensb** [comment]
Hi, we also have a Mt171 but I cannot get it into high precision mode, the IR interface only reports 0.1 kWh steps. The utility says there is no PIN and no configuration options.
How did you get yours to report higher wattage precision? 
Thanks :-)

**Comment by llagendijk** [comment]
Sorry, I have no idea what utility you are referring  to. As said above I not even  have an ME162 anymore, so I cannot even check what that meter returned. I always based development on what the meter returned, so I am afraid I cannot be of any help here.

**Comment by jensb** [comment]
I was actually hoping @yctn would reply. :-) 
I also have a Mt171 like s?he mentioned in the bug report, but I don't get half as many data points as in the log output.
The "utility" is our local electricity supplier.

**Comment by robster7674** [comment]
QQ: is there a way to disable the smart functionality on MT171?
