### ISSUE TITLE
Error in calculating production

### ISSUE THREAD

**Issue by tkorstanje** [llagendijk/iskra-me162#3]
When using this (very useful!!) script for my Iskra ME-162, I found that I always get nill for the current production. I found that line 259 of the executable contains an error. It now reads:
`production = int((current_readings.total_return - current_readings.total_return) / interval * 3600)`
which by definition is nill. Obviously the second current_readings.total_return should be previous_readings.total_return. This should give the correct current production.

**Comment by tkorstanje** [comment]
Unfortunately that didn't fix everything, I found another problem. Line 50 now reads:
`		self.total_return = self.get_wh( "2.8.1", ir_lines)`
which should be 2.8.0 (that's the total of 2.8.1 and 2.8.2). 
These 2 changes makes the script correctly writing out the current production to domoticz

**Comment by tkorstanje** [comment]
Changed this into a fork + pull request, see [here](https://github.com/llagendijk/iskra-me162/pull/4)

**Comment by llagendijk** [comment]
hi
Thanks for the PR. I no longer have an ME162, so I can't test your chnges. I trust they are correct , so I will merge them anyway.
